import process from "node:process";
import * as esbuild from "esbuild";

const production = process.argv[2] === "production";
const banner = "/* This file is generated by esbuild. Edit the TypeScript source in src/ instead. */";

const buildOptions = {
  banner: { js: banner },
  entryPoints: {
    main: "src/main.ts",
    styles: "src/styles.css",
  },
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  platform: "browser",
  format: "cjs",
  define: {
    "process.env.NODE_ENV": JSON.stringify(production ? "production" : "development"),
  },
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  minify: production,
  outdir: ".",
};

if (production) {
  await esbuild.build(buildOptions);
} else {
  const context = await esbuild.context(buildOptions);
  await context.watch();
}
