import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "node:process";

const production = process.argv[2] === "production";
const banner = "/* This file is generated by esbuild. Edit the TypeScript source in src/ instead. */";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: {
    main: "src/main.ts",
    styles: "src/styles.css",
  },
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  define: {
    "process.env.NODE_ENV": JSON.stringify(production ? "production" : "development"),
  },
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
  outdir: ".",
  entryNames: "[name]",
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
